POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email" : "colina.campbell.jr@gmail.com",
    "password" : "my_password"
}

###

GET http://localhost:3000/api/workspace/4/artifact/access-users-collection?artID=7

###

GET http://localhost:3000/api/workspace/4/artifact/as-workspace-artifact?artID=7

###
DELETE http://localhost:3000/api/workspace/1/delete